language: php
php:
  - '5.6'
before_install:
  - php /home/travis/.phpenv/versions/5.6/bin/composer.phar self-update
before_script:
  - composer install
script: php vendor/bin/phpunit --configuration phpunit.xml tests/EmailTest.php