language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
before_install:
- php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar.self -update
before_script:
- composer install
script: phpunit -- configuation phpunit.xml --coverage-text